### ISSUE TITLE
Measurement in progress error

### ISSUE THREAD

**Issue by jessequinn** [AFMD/keithley-2636#1]
The following error is received:

----------------------------------------
Uploaded TSP script:  output-charact.tsp
Measurement in progress...
Traceback (most recent call last):
  File "./test.py", line 18, in <module>
    keithley.Output(sample)
  File "/Users/jessequinn/Downloads/keithley-2636-master/k2636.py", line 180, in Output
    df = self.readBuffer()
  File "/Users/jessequinn/Downloads/keithley-2636-master/k2636.py", line 104, in readBuffer
    vg = [float(x) for x in self._query('printbuffer(1, smub.nvbuffer1.n, smub.nvbuffer1.sourcevalues)').split(',')]
  File "/Users/jessequinn/Downloads/keithley-2636-master/k2636.py", line 104, in <listcomp>
    vg = [float(x) for x in self._query('printbuffer(1, smub.nvbuffer1.n, smub.nvbuffer1.sourcevalues)').split(',')]
ValueError: could not convert string to float: 

The following was modified in the output-charact.tsp

-- PARAMETERS
Vdmin = 0.0
Vdmax = -1.0
Vdstep = 0.1

Vgmin = 0.0
Vgmax = -1.0
Vgstep = 0.1

Any idea what is causing this? I am using MAC OSX with the following address 'USB0::0x05E6::0x2636::4042049::INSTR' to the Keithley 2636B

**Comment by peregrinescode** [comment]
Hi Jesse, only just seen this - have you fixed it? If not I will take a look.

**Comment by jessequinn** [comment]
i have not been able to fix.

**Comment by peregrinescode** [comment]
In the output-charact.tsp, try:

-- PARAMETERS
Vdmin = 0.0
Vdmax = 10
Vdstep = -0.1

Vgmin = 0.0
Vgmax = 10
Vgstep = -0.1

The above will achieve the scan range you want. The problem is with how I have defined things. Vdmax and Vgmax really mean the total number of steps not the max value. I will update the code to make it more comprehensible

**Comment by jessequinn** [comment]
cannot try now will in future. the other thing i wanted to do was measure hysteresis a forward and reverse scan for both output and transfer. can you help with this?

**Comment by peregrinescode** [comment]
For sure - the newest version of the code runs a transfer scan both forwards and backwards. To do an output scan in reverse just remove the negative sign from Vdstep and VgStep.

Let me know if it works for you
